### ISSUE TITLE
CrashCourse：Physics

### ISSUE THREAD

**Issue by AAAlimjan** [AAAlimjan/ComingBack#8]
B站：https://www.bilibili.com/video/av38506067

- [x] P11 Motion in a Straight Line_ Crash Course Physics #1
- [ ] P22 Derivatives_ Crash Course Physics #2
- [ ] P33 Integrals_ Crash Course Physics #3
- [ ] P44 Vectors and 2D Motion_ Crash Course Physics #4
- [ ] P55 Newton's Laws_ Crash Course Physics #5
- [ ] P66 Friction_ Crash Course Physics #6
- [ ] P77 Uniform Circular Motion_ Crash Course Physics #7
- [ ] P88 Newtonian Gravity_ Crash Course Physics #8
- [ ] P99 Work, Energy, and Power_ Crash Course Physics #9
- [ ] P1010 Collisions_ Crash Course Physics #10
- [ ] P1111 Rotational Motion_ Crash Course Physics #11
- [ ] P1212 Torque_ Crash Course Physics #12
- [ ] P1313 Statics_ Crash Course Physics #13
- [ ] P1414 Fluids at Rest_ Crash Course Physics #14
- [ ] P1515 Fluids in Motion_ Crash Course Physics #15
- [ ] P1616 Simple Harmonic Motion_ Crash Course Physics #16
- [ ] P1717 Traveling Waves_ Crash Course Physics #17
- [ ] P1818 Sound_ Crash Course Physics #18
- [ ] P1919 The Physics of Music_ Crash Course Physics #19
- [ ] P2020 Temperature_ Crash Course Physics #20
- [ ] P2121 Kinetic Theory and Phase Changes_ Crash Course Physics #21
- [ ] P2222 The Physics of Heat_ Crash Course Physics #22
- [ ] P2323 Thermodynamics_ Crash Course Physics #23
- [ ] P2424 Engines_ Crash Course Physics #24
- [ ] P2525 Electric Charge_ Crash Course Physics #25
- [ ] P2626 Electric Fields_ Crash Course Physics #26
- [ ] P2727 Voltage, Electric Energy, and Capacitors_ Crash Course Physics #27
- [ ] P2828 Electric Current_ Crash Course Physics #28
- [ ] P2929 DC Resistors & Batteries_ Crash Course Physics #29
- [ ] P3032Magnetism_ Crash Course Physics #32
- [ ] P3133 Ampère's Law_ Crash Course Physics #33
- [ ] P3234 Induction - An Introduction_ Crash Course Physics #34
- [ ] P3335 How Power Gets to Your Home_ Crash Course Physics #35
- [ ] P3436 AC Circuits_ Crash Course Physics #36
- [ ] P3537 Maxwell's Equations_ Crash Course Physics #37
- [ ] P3638 Geometric Optics_ Crash Course Physics #38
- [ ] P3739 Light Is Waves_ Crash Course Physics #39
- [ ] P3840 Spectra Interference_ Crash Course Physics #40
- [ ] P3941 Optical Instruments_ Crash Course Physics #41
- [ ] P4042 Special Relativity_ Crash Course Physics #42
- [ ] P4143 Quantum Mechanics - Part 1_ Crash Course Physics #43
- [ ] P4244 Quantum Mechanics - Part 2_ Crash Course Physics #44
- [ ] P4331 Capacitors and Kirchhoff_ Crash Course Physics #31
- [ ] P4430 Circuit Analysis_ Crash Course Physics #30
- [ ] P4546 Astrophysics and Cosmology_ Crash Course Ph
